### ISSUE TITLE
Kein -r im CLI wenn nur ein Repo angelegt ist

### ISSUE THREAD

**Issue by f-breidenstein** [mweinelt/aurblobs#1]
Wenn eh nur 1 Repository configuriert ist, sollte man das -r im CLI aufruf weglassen können, da es ja eindeutig ist welches gemeint ist

**Comment by mweinelt** [comment]
Die Struktur des CLI hat sich durch Migration auf `click` geändert, das Feature ist aber bisher noch nicht verbaut.

**Comment by f-breidenstein** [comment]
Würde das Repo trotzdem lieber mit "-r" angeben als einfach als argument ohne switch davor. Macht die sache eindeutiger

**Comment by mweinelt** [comment]
Dann muss die Option required sein, falls mehr als ein Repository existiert.
